# # # print('Hello World')
# # # print("name\t Deepak")
# # # print("Line a \\n line b")
# # # print(" \\\" \\\' ")
# # # print((4-2)/(3+2))
# # # print(round(2/5,2))
# # # print(3**4)
# # name = input("Type your name ")
# # print("Hello "+ name)
# # age = input("What is your age? ")
# # print( name + " your age is " + age)
# # number_1 = int(input("Enter the first number "))
# # number_2 = int(input("Enter the value of second number "))
# # sum = (number_1 + number_2)
# # print("The sum of "+ str(number_1) + " and " + str(number_2) + " is " + str(sum)  )
# name, age =  "Deepak", 24
# print("name is "  + name + " and age is " + str(age))
name = "deepak kumar sinha"
# print(f"length of string {len(name)}")
print(f"name is {name.count('a')}")